# 단일 계층 신경망 선언

In [2]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

print("x = ", x)
print("y = ", y)
print("w = ", w)
print("b = ", b)
print("z = ", z)
print("loss = ", loss)

x =  tensor([1., 1., 1., 1., 1.])
y =  tensor([0., 0., 0.])
w =  tensor([[-0.7516,  1.0251,  1.2397],
        [ 0.4363,  0.0377,  1.1696],
        [-0.3732, -1.0043,  1.5362],
        [ 0.3138, -0.8930,  1.0109],
        [ 0.9929, -0.9790,  0.2220]], requires_grad=True)
b =  tensor([-0.6381,  1.1103,  0.0114], requires_grad=True)
z =  tensor([-0.0200, -0.7031,  5.1898], grad_fn=<AddBackward0>)
loss =  tensor(2.0936, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


## 1. Tensors, Functions and Computational Graph

In [3]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x7f7ec08a6f10>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7f7ec08a6d10>


## 2. Computing Gradients

In [4]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.1650, 0.1104, 0.3315],
        [0.1650, 0.1104, 0.3315],
        [0.1650, 0.1104, 0.3315],
        [0.1650, 0.1104, 0.3315],
        [0.1650, 0.1104, 0.3315]])
tensor([0.1650, 0.1104, 0.3315])


## 3. Disabling Gradient Tracking

In [5]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [6]:
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False


## 5. 

In [8]:
inp = torch.eye(5, requires_grad=True)
print("inp = ", inp)
out = (inp+1).pow(2)
print("out", out)
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

inp =  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], requires_grad=True)
out tensor([[4., 1., 1., 1., 1.],
        [1., 4., 1., 1., 1.],
        [1., 1., 4., 1., 1.],
        [1., 1., 1., 4., 1.],
        [1., 1., 1., 1., 4.]], grad_fn=<PowBackward0>)
First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
